### PR TITLE
Upgrade dependencies versions

### PR DESCRIPTION
**Pull request by jamyouss**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  |  no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

Hello,
This pull request upgrade composer dependencies versions.

### CODE REVIEW

**Comment by jamyouss** [comment]
@egeloen we should considering to update the minimum php version to 5.6.
What do you think ?

**Comment by egeloen** [comment]
For now, I'm not in favor of bumping PHP to 5.6. Basically, I would like to do it one time for all my libraries/bundles...

Anyway, can you explain me why would you like to bump Symfony to 3.1 and don't allow Symfony 3.0?

**Comment by jamyouss** [comment]
> Anyway, can you explain me why would you like to bump Symfony to 3.1 and don't allow Symfony 3.0? Tests are green for this version: https://github.com/egeloen/IvoryLuceneSearchBundle/blob/master/.travis.yml#L47-L48

@egeloen You're right, my bad :-( 
Going to change this mistake.

**Comment by egeloen** [comment]
Closing as if we drop your changes related to symfony version, there is nothing more in this PR.

**Pull request closed without merging**
